sonar.projectKey=Blazedemo-Playwright
sonar.projectName=Blazedemo playwright
sonar.projectVersion=1.0
sonar.language=ts
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,dist/**,test/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000/
sonar.token=squ_0e6bdc0c713a4cb5f4f76e0887fb34ad199b7740