## Continous integration
name: Playwright Tests
on:
  push:
    branches: [ main, master, qa ]
  pull_request:
    branches: [ main, master, qa]
jobs:
  test:
    timeout-minutes: 60 ## Tiempo maximo de pruebas
    runs-on: ubuntu-latest ## Maquina virtual donde se ejecutaran las pruebas
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.2 #Versión de node
      - name: Install dependencies
        run: npm ci #Install CI dependencies
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ## Instalación de navegadores
      - name: Run Playwright tests
        run: npx Playwright test ## Comando de ejecución de pruebas
      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
